### PR TITLE
Do string escaping for all endpoints and unescaping for string literal

### LINKED ISSUE #592: JSON API responses contain invalid escape sequences
## Summary

The HTTP API returns JSON with invalid escape sequences in string property values, causing `JSON.parse()` to fail in clients.

### 1. Invalid `\'` escape sequence (77 occurrences in `shipping` graph)

`\'` is not a valid JSON escape. Only `\"`, `\\`, `\/`, `\b`, `\f`, `\n`, `\r`, `\t`, and `\uXXXX` are valid.

**Example from `GET /get_nodes`:**
```json
{"name":"Lloyd\'s of London"}
```

**Expected:**
```json
{"name":"Lloyd's of London"}
```

Single quotes do not need escaping in JSON strings.

### 2. Unescaped `"` inside string values

Double quotes inside property values are not escaped, producing structurally invalid JSON.

**Example from `GET /get_nodes`:**
```json
{"iso_equipment_name":"40ft high cube container (9'6\")"}
```

The `"` after `6` is unescaped and terminates the string prematurely, causing a parse error:
```
SyntaxError: Expected ',' or '}' after property value in JSON at position 138005
```

**Expected:**
```json
{"iso_equipment_name":"40ft high cube container (9'6\\\")"}
```

## Reproduction

```bash
# Start turingdb with the shipping graph loaded
turingdb start -load shipping

# Fetch all nodes — response fails JSON.parse() in JavaScript
curl -s -X POST 'http://localhost:6666/get_nodes?graph=shipping' \
  -H 'Content-Type: application/json' \
  -d '{"nodeIDs":[0,1,2,3,4,5,6,7,8,9]}' | node -e "
    let t=''; process.stdin.on('data',d=>t+=d); process.stdin.on('end',()=>{
      try { JSON.parse(t); console.log('OK') }
      catch(e) { console.log(e.message) }
    })"
```

With enough nodes (e.g. all 3209 in the shipping graph), the response hits a property containing `\'` or unescaped `"`, and `JSON.parse()` throws.

## Impact

The visualizer's `MATCH (n) RETURN n LIMIT 10000` query returns an empty canvas because `getNodes()` fails silently on JSON parse, and React Query retries in a loop.

## Workaround

Client-side sanitization before parsing: `text.replace(/\\'/g, "'")` handles the `\'` case, but the unescaped `"` requires a more complex fix.

### PR DESCRIPTION
**Pull request by rjb32**
* The /get_nodes endpoint returns invalid JSON when string properties contain single quotes (\') or unescaped double quotes. Creates a minimal regress test to reproduce.
* Escaping strings in all REST endpoints
* Unescape strings that may be escaped during query parsing when creating StringLiteral

Fixes #592

### CODE REVIEW

File: query/AST/Literal.cpp [hunk 1]
```diff
@@ -28,6 +28,29 @@ DoubleLiteral* DoubleLiteral::create(CypherAST* ast, double value) {
     return literal;
 }
 
+StringLiteral::StringLiteral(std::string_view raw) {
```
Comment (rjb32) [inline query/AST/Literal.cpp]: Do this in the create function. Never do significant work in constructors

File: query/AST/Literal.cpp [hunk 2]
```diff
@@ -28,8 +56,15 @@ DoubleLiteral* DoubleLiteral::create(CypherAST* ast, double value) {
     return literal;
 }
 
+StringLiteral::StringLiteral() {
+}
```
Comment (cyrusknopf) [inline query/AST/Literal.cpp]:
```suggestion
StringLiteral::StringLiteral()
{
}
```

File: query/AST/Literal.cpp [hunk 3]
```diff
@@ -4,6 +4,34 @@
...
 
+namespace {
+
+void unescapeString(std::string_view raw, std::string& out) {
+    out.clear();
+    out.reserve(raw.size());
+
+    for (size_t i = 0; i < raw.size(); i++) {
+        if (raw[i] == '\\' && i + 1 < raw.size()) {
+            char next = raw[i + 1];
```
Comment (sulaimansuhas) [inline query/AST/Literal.cpp]: const here

**Review by cyrusknopf — APPROVED** [review]

**Review by sulaimansuhas — APPROVED** [review]
